version: '2'
services:
  db:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=simple
      - MYSQL_DATABASE=eduroam
      - MYSQL_USER=manager
      - MYSQL_PASSWORD=manager
    volumes:
      - ./.data:/var/lib/mysql
    restart: always